site_name: RDA Fair Mappings Working Group
theme:
  name: material
  icon:
    edit: material/pencil 
  features:
    - content.action.edit
    #- navigation.tabs
    #- toc.integrate
    #- navigation.sections
    #- navigation.top
    - search.suggest
    - search.highlight
    #- content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - md_in_html
  - tables

extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

nav:
  - About our work: index.md
  - Use Cases:
      - Overview: use-cases.md
      - Case Studies:
          - Lunaris: case-study/case-study-lunaris.md
          - Mondo Ontology: case-study/case-study-mondo.md
          - Uberon Ontology: case-study/case-study-uberon.md
          - Integrated Carbon Observation System: case-study/case-study-icos.md
          - British Oceanographic Data Centre: case-study/case-study-bodc.md
          - INRAE Thesaurus: case-study/case-study-inrae.md
          - Circular Economy Ontologies: case-study/case-study-ceon.md
          - Wheat Ontology: case-study/case-study-wheatontology.md
          - NII Data Governance: case-study/case-study-nii.md
          - I-ADOPT: case-study/case-study-i-adopt.md
          - DLITE transform: case-study/case-study-dlite-transform.md
          - DLITE: case-study/case-study-dlite.md
          - COMP-LOINC: case-study/case-study-comp-loinc.md
          - Information Extraction from Literature: case-study/case-study-ontogpt-ie.md
          - Schema element mapping with LinkML-Map: case-study/case-study-linkml-map.md
          - Schema subsetting with LinkML-Map: case-study/case-study-linkml-map-subset.md
          - Schema normalization with LinkML-Map: case-study/case-study-linkml-map-normalization.md
          - FoodOn to FoodEx2 mapping: case-study/case-study-food.md
          - Mapping LGBTQ+-related thesauri: case-study/case-study-lgbtq.md
          - Fresh Catalog: case-study/case-study-fresh.md
          - BFO-PROV-O: case-study/case-study-bfoprov.md
          - WOD to ICES platforms: case-study/case-study-wod-ices.md
          - DCAT-AP-DataCite: case-study/case-study-dcat-ap-datacite.md
          - DCAT-AP-Schema.org: case-study/case-study-dcat-ap-schemaorg.md
  - FAIR Mapping recommendations: recommendation.md
  - Decision log of the Working Group: decision-log.md
  - Related efforts: related-efforts.md
  - Resources about FAIR mappings: resources.md
repo_url: https://github.com/mapping-commons/rda-fair-mappings/
site_url: https://mapping-commons.github.io/rda-fair-mappings/
edit_uri: edit/main/src/docs/
